import { parseAbiItem, type Address } from 'viem';
import { ARCSIGNAL_ABI, ARCSIGNAL_ADDRESS, publicClient } from './contracts';
import type { AIAnalysis, Market, MarketCategory, MarketOutcome } from './types';

interface ContractMarket {
  marketId: string;
  category: string;
  resolutionTime: bigint;
  followPool: bigint;
  fadePool: bigint;
  resolved: boolean;
  outcome: number;
}

export interface SerializableMarket extends Omit<Market, 'followPool' | 'fadePool'> {
  followPool: string;
  fadePool: string;
}

const marketCreatedEvent = parseAbiItem(
  'event MarketCreated(string marketId, string category, uint256 resolutionTime)',
);
const logBlockRange = 9_999n;

function isAddress(value: string | undefined): value is Address {
  return /^0x[a-fA-F0-9]{40}$/.test(value ?? '');
}

function mapCategory(category: string): MarketCategory {
  const normalized = category.toUpperCase();
  if (normalized === 'CRYPTO' || normalized === 'FOOTBALL') {
    return normalized;
  }

  throw new Error(`Unsupported market category: ${category}`);
}

function mapOutcome(resolved: boolean, outcome: number): MarketOutcome {
  if (!resolved) {
    return 'PENDING';
  }

  if (outcome === 0) {
    return 'FOLLOW';
  }

  if (outcome === 1) {
    return 'FADE';
  }

  return 'CANCELLED';
}

function fallbackAnalysis(marketId: string, category: MarketCategory): AIAnalysis {
  return {
    probability: 50,
    confidence: 50,
    prediction: 'YES',
    summary: `${category} market generated by ArcSignal agents. The deployed contract stores the market ID, category, resolution time, pools, and outcome on-chain.`,
    bullCase: `Follow wins if this market resolves in favor of: ${marketId}`,
    bearCase: 'Fade wins if the market resolves against the AI signal.',
    keyFactors: [
      'Market metadata is anchored by the on-chain market ID.',
      'Pool sizes update from ARC Testnet contract state.',
      'Resolution is executed through the deployed ARCSignal resolver.',
    ],
    riskFactors: ['On-chain market contract does not store AI analysis JSON.'],
    sources: category === 'FOOTBALL' ? ['API-Football', 'ARC Testnet'] : ['CoinGecko', 'ARC Testnet'],
    generatedAt: new Date().toISOString(),
  };
}

export function mapContractMarket(data: ContractMarket): Market {
  const category = mapCategory(data.category);
  return {
    id: data.marketId,
    marketId: data.marketId,
    question: data.marketId,
    category,
    resolutionTime: Number(data.resolutionTime),
    analysis: fallbackAnalysis(data.marketId, category),
    followPool: data.followPool,
    fadePool: data.fadePool,
    resolved: data.resolved,
    outcome: mapOutcome(data.resolved, data.outcome),
  };
}

export function serializeMarket(market: Market): SerializableMarket {
  return {
    ...market,
    followPool: market.followPool.toString(),
    fadePool: market.fadePool.toString(),
  };
}

export async function getMarketIdsFromChain(): Promise<string[]> {
  if (!isAddress(ARCSIGNAL_ADDRESS)) {
    return [];
  }

  const latestBlock = await publicClient.getBlockNumber();
  const configuredStart = BigInt(process.env.NEXT_PUBLIC_ARCSIGNAL_DEPLOY_BLOCK ?? 0);
  const logs = [];

  for (let fromBlock = configuredStart; fromBlock <= latestBlock; fromBlock += logBlockRange + 1n) {
    const toBlock = fromBlock + logBlockRange > latestBlock ? latestBlock : fromBlock + logBlockRange;
    logs.push(
      ...(await publicClient.getLogs({
        address: ARCSIGNAL_ADDRESS,
        event: marketCreatedEvent,
        fromBlock,
        toBlock,
      })),
    );
  }

  return Array.from(
    new Set(
      logs
        .map((log) => log.args.marketId)
        .filter((marketId): marketId is string => typeof marketId === 'string' && marketId.length > 0),
    ),
  );
}

export async function getMarketsFromChain(): Promise<Market[]> {
  const marketIds = await getMarketIdsFromChain();
  const markets: Market[] = [];

  for (const marketId of marketIds) {
    const data = (await publicClient.readContract({
      address: ARCSIGNAL_ADDRESS,
      abi: ARCSIGNAL_ABI,
      functionName: 'getMarket',
      args: [marketId],
    })) as ContractMarket;

    if (data.marketId) {
      markets.push(mapContractMarket(data));
    }
  }

  return markets.sort((a, b) => b.resolutionTime - a.resolutionTime);
}
