import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Stitch design tokens ──────────────────────────────
        'arc-bg':      '#131313',
        'arc-surface': '#0f172a',
        'arc-border':  '#1e293b',
        'arc-purple':  '#ddb7ff',
        'arc-teal':    '#4fdbc8',
        'arc-red':     '#ffb4ab',
        'arc-text':    '#e5e2e1',
        'arc-muted':   '#94a3b8',
        'arc-card':    '#1c1b1b',

        // ── Legacy tokens (kept for other pages) ──────────────
        'on-error': '#690005',
        'on-tertiary': '#003824',
        'primary-fixed': '#e1e0ff',
        background: '#131313',
        'on-surface': '#e2e2e5',
        'on-secondary-fixed': '#0d1c2d',
        'on-primary': '#1000a9',
        'secondary-fixed': '#d4e4fa',
        'on-secondary': '#233143',
        'inverse-surface': '#e2e2e5',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed': '#002113',
        'primary-fixed-dim': '#c0c1ff',
        'primary-container': '#8083ff',
        'surface-container-highest': '#333537',
        'on-primary-container': '#0d0096',
        'surface-bright': '#37393c',
        'tertiary-fixed': '#6ffbbe',
        'outline-variant': '#464554',
        'on-surface-variant': '#c7c4d7',
        'on-primary-fixed-variant': '#2f2ebe',
        'surface-dim': '#111416',
        'on-secondary-fixed-variant': '#39485a',
        primary: '#c0c1ff',
        'on-tertiary-container': '#000703',
        'tertiary-container': '#00885d',
        'error-container': '#93000a',
        surface: '#111416',
        outline: '#908fa0',
        'on-tertiary-fixed-variant': '#005236',
        'secondary-fixed-dim': '#b9c8de',
        'surface-container-high': '#282a2c',
        'surface-tint': '#c0c1ff',
        secondary: '#b9c8de',
        tertiary: '#4edea3',
        'on-secondary-container': '#a7b6cc',
        'secondary-container': '#39485a',
        'surface-container-lowest': '#0c0e10',
        'surface-variant': '#333537',
        'surface-container': '#1e2022',
        'surface-container-low': '#1a1c1e',
        'inverse-on-surface': '#2f3133',
        'on-background': '#e2e2e5',
        'on-primary-fixed': '#07006c',
        'inverse-primary': '#494bd6',
        'tertiary-fixed-dim': '#4edea3',
        error: '#ffb4ab',
      },
      fontFamily: {
        mono:   ['var(--font-jetbrains-mono)', 'monospace'],
        sans:   ['var(--font-inter)', 'sans-serif'],
        hanken: ['var(--font-hanken)', 'sans-serif'],
      },
      keyframes: {
        marquee: {
          '0%':   { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'pulse-dot': {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '0.3' },
        },
      },
      animation: {
        marquee:    'marquee 40s linear infinite',
        'pulse-dot': 'pulse-dot 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};

export default config;
