import Sidebar from '@/components/layout/Sidebar';
import { BookOpen, Droplets, TrendingUp, ShieldCheck, Coins } from 'lucide-react';

export default function GuidePage() {
  return (
    <div className="flex min-h-screen bg-[#131313]">
      <Sidebar />
      <main className="lg:ml-[264px] pt-24 pb-24 md:pb-8 flex-1 min-w-0 min-h-screen">
        <div className="max-w-[800px] mx-auto w-full p-6 lg:p-8">
          
          <header className="mb-10">
            <div className="inline-flex items-center justify-center w-12 h-12 rounded-xl bg-[#ddb7ff]/10 border border-[#ddb7ff]/20 text-[#ddb7ff] mb-4">
              <BookOpen className="w-6 h-6" />
            </div>
            <h1 className="font-[family-name:var(--font-hanken)] text-4xl font-bold text-white tracking-tight mb-3">
              How to Play ArcSignal
            </h1>
            <p className="text-[#94a3b8] text-lg leading-relaxed">
              Welcome to ArcSignal, the premier decentralized prediction market powered by AI. 
              Learn how to connect, trade, and earn rewards by accurately forecasting market outcomes.
            </p>
          </header>

          <div className="space-y-8">
            
            {/* Step 1 */}
            <section className="bg-[#1c1b1b] border border-[#3a3939] rounded-2xl p-6 md:p-8 shadow-xl">
              <div className="flex items-start gap-4">
                <div className="mt-1 flex-shrink-0 w-10 h-10 rounded-full bg-[#4fdbc8]/10 flex items-center justify-center text-[#4fdbc8]">
                  <Droplets className="w-5 h-5" />
                </div>
                <div>
                  <h2 className="text-xl font-bold text-[#e5e2e1] mb-2 font-[family-name:var(--font-hanken)]">
                    1. Get Testnet USDC
                  </h2>
                  <p className="text-[#94a3b8] text-sm leading-relaxed mb-4">
                    ArcSignal operates on the Arc Testnet using testnet USDC. Before you can place a position, you need to fund your wallet.
                  </p>
                  <ul className="list-disc list-inside text-sm text-[#94a3b8] space-y-2 ml-1">
                    <li>Click the <strong>Connect Wallet</strong> button in the top right.</li>
                    <li>Once connected, click your address to open the wallet dropdown.</li>
                    <li>Click the <strong>Get USDC</strong> button, or the <strong>+</strong> icon in the header.</li>
                    <li>You will be redirected to the Circle Faucet to claim your testnet tokens.</li>
                  </ul>
                </div>
              </div>
            </section>

            {/* Step 2 */}
            <section className="bg-[#1c1b1b] border border-[#3a3939] rounded-2xl p-6 md:p-8 shadow-xl">
              <div className="flex items-start gap-4">
                <div className="mt-1 flex-shrink-0 w-10 h-10 rounded-full bg-[#ddb7ff]/10 flex items-center justify-center text-[#ddb7ff]">
                  <TrendingUp className="w-5 h-5" />
                </div>
                <div>
                  <h2 className="text-xl font-bold text-[#e5e2e1] mb-2 font-[family-name:var(--font-hanken)]">
                    2. Browse Markets
                  </h2>
                  <p className="text-[#94a3b8] text-sm leading-relaxed mb-4">
                    Navigate to the <strong>Markets</strong> page to see active predictions generated by our AI operators.
                  </p>
                  <div className="bg-[#131313] border border-[#3a3939] rounded-lg p-4 mb-4">
                    <p className="text-sm text-[#e5e2e1] mb-2 font-bold">Understanding Market Cards</p>
                    <p className="text-xs text-[#94a3b8]">
                      Each card displays a specific prediction (e.g., "Will BTC cross $100k?"). You will see the total volume staked, the current liquidity pools for both sides, and the deadline for the outcome to be resolved.
                    </p>
                  </div>
                </div>
              </div>
            </section>

            {/* Step 3 */}
            <section className="bg-[#1c1b1b] border border-[#3a3939] rounded-2xl p-6 md:p-8 shadow-xl">
              <div className="flex items-start gap-4">
                <div className="mt-1 flex-shrink-0 w-10 h-10 rounded-full bg-[#ffb4ab]/10 flex items-center justify-center text-[#ffb4ab]">
                  <ShieldCheck className="w-5 h-5" />
                </div>
                <div>
                  <h2 className="text-xl font-bold text-[#e5e2e1] mb-2 font-[family-name:var(--font-hanken)]">
                    3. Place Your Position
                  </h2>
                  <p className="text-[#94a3b8] text-sm leading-relaxed mb-4">
                    Once you find a market you want to trade on, you must decide whether to align with the AI's prediction or bet against it.
                  </p>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                    <div className="bg-[#131313] border border-[#4fdbc8]/20 rounded-lg p-4">
                      <div className="text-[#4fdbc8] font-bold text-sm mb-1 uppercase tracking-wider font-[family-name:var(--font-jetbrains-mono)]">Follow AI</div>
                      <p className="text-xs text-[#94a3b8]">
                        Stake your USDC believing the AI's prediction is correct. If the event resolves in favor of the prediction, you win a share of the Fade pool.
                      </p>
                    </div>
                    <div className="bg-[#131313] border border-[#ffb4ab]/20 rounded-lg p-4">
                      <div className="text-[#ffb4ab] font-bold text-sm mb-1 uppercase tracking-wider font-[family-name:var(--font-jetbrains-mono)]">Fade AI</div>
                      <p className="text-xs text-[#94a3b8]">
                        Stake your USDC believing the AI's prediction is wrong. If the event resolves opposite to the prediction, you win a share of the Follow pool.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            {/* Step 4 */}
            <section className="bg-[#1c1b1b] border border-[#3a3939] rounded-2xl p-6 md:p-8 shadow-xl">
              <div className="flex items-start gap-4">
                <div className="mt-1 flex-shrink-0 w-10 h-10 rounded-full bg-[#e8a355]/10 flex items-center justify-center text-[#e8a355]">
                  <Coins className="w-5 h-5" />
                </div>
                <div>
                  <h2 className="text-xl font-bold text-[#e5e2e1] mb-2 font-[family-name:var(--font-hanken)]">
                    4. Claim Winnings
                  </h2>
                  <p className="text-[#94a3b8] text-sm leading-relaxed mb-4">
                    When a market reaches its resolution date, an oracle determines the outcome. If your position was correct, you are entitled to your original stake plus your share of the losing pool.
                  </p>
                  <ul className="list-disc list-inside text-sm text-[#94a3b8] space-y-2 ml-1">
                    <li>Navigate to the <strong>Portfolio</strong> tab.</li>
                    <li>Look for the <strong>Unclaimed Winnings</strong> section at the top of the page.</li>
                    <li>Click the <strong>Claim</strong> button next to any resolved market to transfer the USDC to your wallet.</li>
                  </ul>
                </div>
              </div>
            </section>

          </div>
          
          <div className="mt-12 text-center pb-12">
            <p className="text-xs text-[#94a3b8] font-[family-name:var(--font-jetbrains-mono)]">
              Ready to start predicting?
            </p>
            <a href="/markets" className="inline-block mt-4 bg-[#ddb7ff] text-[#0f172a] font-bold py-3 px-8 rounded-full hover:brightness-110 transition-all duration-200 shadow-lg shadow-[#ddb7ff]/10">
              Explore Markets
            </a>
          </div>

        </div>
      </main>
    </div>
  );
}
